# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer:4.6.3-standalone
    restart: always
    ports:
      - 8080:8080
