# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:9.6-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  adminer:
    image: adminer:4.6.3-standalone
    restart: always
    ports:
      - 8080:8080

volumes:
  dbdata: