"""empty message

Revision ID: ed1fbbc3745b
Revises: 605fb965dcff
Create Date: 2018-07-11 10:56:43.743225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed1fbbc3745b'
down_revision = '605fb965dcff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('deadline', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'deadline')
    # ### end Alembic commands ###
